const motivationalQuotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future depends on what you do today. - Mahatma Gandhi",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "There are no traffic jams along the extra mile. - Roger Staubach",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Your attitude, not your aptitude, will determine your altitude. - Zig Ziglar",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "There are no traffic jams along the extra mile. - Roger Staubach",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Success is not just about making money. It's about making a difference. - Unknown",
    "Run fast, still last. - Brandon Le",
    "Don't be afraid of failure, because at the end of the day, it's night - Alicia Filomeno",
    "Fishing is awesome! - Ivan Lin"
  ];
  
export default motivationalQuotes;